//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSSQLDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person : Models.DTOConversion.IDBModel
    {
        public int IDP { get; set; }
        public string Name { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string PhoneNumber { get; set; }
    
        public virtual HealthCareWorker HealthCareWorker { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
